config/routes.rb
Kareerweb::Application.routes.draw do
  
  resources :academics

  resources :skills

  devise_for :users

  resources :resumes
  root :to => "resumes#profile"
  match '/:controller/:action/:id' => '#index'

end

app/models/academic.rb
class Academic < ActiveRecord::Base
  attr_accessible :institute, :percentage, :qualification, :user_id, :year_of_passout

  belongs_to	:user
end

app/controllers/academics_controller.rb
class AcademicsController < ApplicationController
  # GET /academics
  # GET /academics.json
  def index
    @academics = Academic.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /academics/1
  # GET /academics/1.json
  def show
    @academic = Academic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /academics/new
  # GET /academics/new.json
  def new
    @academic = Academic.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /academics/1/edit
  def edit
    @academic = Academic.find(params[:id])
  end

  # POST /academics
  # POST /academics.json
  def create
    @academic = Academic.new(params[:academic])

    respond_to do |format|
      if @academic.save
        redirect_to(@academic)
        flash[:notice] = 'Academic was successfully created.'
      else
        render :file => "/academics/new"
      end
    end
  end

  # PUT /academics/1
  # PUT /academics/1.json
  def update
    @academic = Academic.find(params[:id])

    respond_to do |format|
      if @academic.update_attributes(params[:academic])
        redirect_to(@academic)
        flash[:notice] ='Academic was successfully updated.'
        format.json { head :no_content }
      else
        render :file => "/academics/edit"
      end
    end
  end

  # DELETE /academics/1
  # DELETE /academics/1.json
  def destroy
    @academic = Academic.find(params[:id])
    @academic.destroy

    respond_to do |format|
      format.html { redirect_to academics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/academics_helper.rb
module AcademicsHelper
end

app/views/academics/_form.html.erb
<%= form_for(@academic) do |f| %>
  <% if @academic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@academic.errors.count, "error") %> prohibited this academic from being saved:</h2>

      <ul>
      <% @academic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :qualification %><br />
    <%= f.text_field :qualification %>
  </div>
  <div class="field">
    <%= f.label :institute %><br />
    <%= f.text_field :institute %>
  </div>
  <div class="field">
    <%= f.label :percentage %><br />
    <%= f.text_field :percentage %>
  </div>
  <div class="field">
    <%= f.label :year_of_passout %><br />
    <%= f.number_field :year_of_passout %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/academics/edit.html.erb
<h1>Editing academic</h1>

<%= render 'form' %>

<%= link_to 'Show', @academic %> |
<%= link_to 'Back', academics_path %>

app/views/academics/index.html.erb
<h1>Listing academics</h1>

<table>
  <tr>
    <th>Qualification</th>
    <th>Institute</th>
    <th>Percentage</th>
    <th>Year of passout</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @academics.each do |academic| %>
  <tr>
    <td><%= academic.qualification %></td>
    <td><%= academic.institute %></td>
    <td><%= academic.percentage %></td>
    <td><%= academic.year_of_passout %></td>
    <td><%= academic.user_id %></td>
    <td><%= link_to 'Show', academic %></td>
    <td><%= link_to 'Edit', edit_academic_path(academic) %></td>
    <td><%= link_to 'Destroy', academic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Academic', new_academic_path %>

app/views/academics/new.html.erb
<h1>New academic</h1>

<%= render 'form' %>

<%= link_to 'Back', academics_path %>

app/views/academics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Qualification:</b>
  <%= @academic.qualification %>
</p>

<p>
  <b>Institute:</b>
  <%= @academic.institute %>
</p>

<p>
  <b>Percentage:</b>
  <%= @academic.percentage %>
</p>

<p>
  <b>Year of passout:</b>
  <%= @academic.year_of_passout %>
</p>

<p>
  <b>User:</b>
  <%= @academic.user_id %>
</p>


<%= link_to 'Edit', edit_academic_path(@academic) %> |
<%= link_to 'Back', academics_path %>