config/routes.rb
Kareerweb::Application.routes.draw do
  
  resources :academics

  resources :skills

  devise_for :users

  resources :resumes
  root :to => "resumes#profile"
  match '/:controller/:action/:id' => '#index'

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :skill_name, :user_id

  belongs_to	:user
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @skill = Skill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /skills/new
  # GET /skills/new.json
  def new
    @skill = Skill.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /skills/1/edit
  def edit
    @skill = Skill.find(params[:id])
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(params[:skill])

    if @skill.save
      flash[:notice] = 'Skill was successfully created.'
      redirect_to(@skill)
    else
      render :file => "/skills/new"
    end
  end

  # PUT /skills/1
  # PUT /skills/1.json
  def update
    @skill = Skill.find(params[:id])

    if @skill.update_attributes(params[:skill])
      flash[:notice] = 'Skill was successfully updated.'
      redirect_to(@skill)
    else
      render :file => "edit"
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skill_name %><br />
    <%= f.text_field :skill_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<h1>Listing skills</h1>

<table>
  <tr>
    <th>Skill name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skills.each do |skill| %>
  <tr>
    <td><%= skill.skill_name %></td>
    <td><%= skill.user_id %></td>
    <td><%= link_to 'Show', skill %></td>
    <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
    <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Skill name:</b>
  <%= @skill.skill_name %>
</p>

<p>
  <b>User:</b>
  <%= @skill.user_id %>
</p>


<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>