config/routes.rb
Kareerweb::Application.routes.draw do
  
  resources :academics

  resources :skills

  devise_for :users

  resources :resumes
  root :to => "resumes#profile"
  match '/:controller/:action/:id' => '#index'

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  attr_accessible :date_of_birth, :email_id, :name, :phone_number, :summary
  validates :phone_number, :length => {:is => 10}, :numericality => { :only_integer => true }
  belongs_to	:user
end

app/controllers/resumes_controller.rb
require 'zip/zip'
class ResumesController < ApplicationController
  before_filter :authenticate_user!
  skip_before_filter :verify_authenticity_token, :only => "upload_file"

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    @resume = Resume.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /resumes/new
  # GET /resumes/new.json
  def new
    @resume = Resume.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /resumes/1/edit
  def edit
    @resume = Resume.find(params[:id])
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(params[:resume])

      if @resume.save
        flash[:notice] = 'Resume was successfully created.'
        redirect_to @resume
      else
        render :file => "/resumes/new"
      end
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update
    @resume = Resume.find(params[:id])
    
    if @resume.update_attributes(params[:resume])
      logger.info"UPDATED"
      flash[:notice] = 'Resume was successfully updated.'
      redirect_to("/resumes/profile/#{current_user.id}")
    else
      render :file => "/resumes/edit"
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy

    respond_to do |format|
      format.html { redirect_to resumes_url }
      format.json { head :no_content }
    end
  end

  def profile
    @resume = current_user.resume
    @skills = current_user.skills
    @academics = current_user.academics
  end

  def upload_file
    save_resume(params[:upload].tempfile,params[:upload].original_filename)
    parser_controller_obj = ParserController.new
    parser_controller_obj.parse(current_user)
    # resume = Resume.new
    # resume.name = "Surupa"
    # resume.phone_number = "9032652151".to_i
    # resume.experience = 3
    # resume.user_id = current_user.id
    # if resume.save
    #   flash[:notice] = "File uploaded successfully"
    #   redirect_to("/resumes/profile/#{current_user.id}")
    # else
    #   FileUtils.rm_r path
    #   flash[:notice] = "Please upload a proper file"
      redirect_to("/resumes/profile/#{current_user.id}")
    # end
  end

  def save_resume(tempfile,original_filename)
    upload_path = "public/resumes/#{current_user.id}/"
    FileUtils.mkdir_p(upload_path)
    path = upload_path + original_filename
    FileUtils.cp tempfile.path, path
    Zip::ZipFile.open(path) do |files|
      files.each do |file|
        f_path = upload_path + "/original/" + file.name
        FileUtils.mkdir_p(File.dirname(f_path))
        files.extract(file, f_path) unless File.exist?(f_path)
      end
    end
  end

end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email_id %><br />
    <%= f.text_field :email_id %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.text_field :date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<h1>Listing resumes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Summary</th>
    <th>Phone number</th>
    <th>Email</th>
    <th>Date of birth</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resumes.each do |resume| %>
  <tr>
    <td><%= resume.name %></td>
    <td><%= resume.summary %></td>
    <td><%= resume.phone_number %></td>
    <td><%= resume.email_id %></td>
    <td><%= resume.date_of_birth %></td>
    <td><%= link_to 'Show', resume %></td>
    <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
    <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/profile.html.erb
<%= current_user.email %>
<% unless @resume.nil? or @resume.blank? %>
  <table>
    <a href="/resumes/edit/<%= @resume.id %>">Edit</a>
    <tr>
      <th align="left">Name: </th><td><%= @resume.name %></td>
    </tr>
    <tr>
      <th align="left">Phone Number: </th><td><%= @resume.phone_number %></td>
    </tr>
    <tr>
      <th align="left">Date of Birth: </th><td><%= @resume.date_of_birth %></td>
    </tr>
    <tr>
      <th align="left">Work Experience: </th><td><%= @resume.experience %></td>
    </tr>
  </table>
<% else %>
  <form action="/resumes/upload_file/<%= current_user.id %>" method="post" enctype="multipart/form-data">
   <p><label for="upload_file">Select File</label>:
     <input type="file" name="upload" size="50"/></p>
   <input type="submit" value="Upload"/>
  </form>
<% end %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resume.name %>
</p>

<p>
  <b>Summary:</b>
  <%= @resume.summary %>
</p>

<p>
  <b>Phone number:</b>
  <%= @resume.phone_number %>
</p>

<p>
  <b>Email:</b>
  <%= @resume.email_id %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @resume.date_of_birth %>
</p>


<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>